# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches: ["main"]
concurrency:
  group: "metrics"
  cancel-in-progress: true
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Denver
          
          plugin_achievements: yes
          plugin_achievements_display: compact
          
          plugin_gists: yes
          
          plugin_languages: yes
          plugin_languages_indepth: yes
          
          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_token: 52ffa34ebbd200da17da5a6c3aef1b2e
          plugin_music_user: FayneAldan
          plugin_music_mode: top
          
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          
          plugin_splatoon: yes
          plugin_splatoon_token: ${{ secrets.SPLATOON_TOKEN }}
          plugin_splatoon_statink: yes
          plugin_splatoon_statink_token: ${{ secrets.SPLATOON_STATINK_TOKEN }}
