# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

concurrency:
  group: "metrics"
  cancel-in-progress: true

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: General
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Denver

          plugin_achievements: yes
          plugin_achievements_display: compact

          plugin_gists: yes

          plugin_languages: yes
          plugin_languages_indepth: yes

          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
          plugin_music_user: RuiNtD

          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

      - name: Splatoon
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: splatoon.png

          base: ""

          plugin_splatoon: yes
          plugin_splatoon_token: ${{ secrets.SPLATOON_TOKEN }}
          plugin_splatoon_statink: yes
          plugin_splatoon_statink_token: ${{ secrets.SPLATOON_STATINK_TOKEN }}
